#!/usr/bin/env python3
"""
Global Documentation Merger
Part of the World's Best Repo Book Generator
"""

import os
import re
import json
from pathlib import Path
from datetime import datetime
from collections import defaultdict

class GlobalMerger:
    """Generate global indexes and comprehensive book"""

    def __init__(self, repo_root: Path, docs_root: Path, manifest_path: Path):
        self.repo_root = Path(repo_root)
        self.docs_root = Path(docs_root)
        self.manifest_path = Path(manifest_path)
        self.manifest = None
        self.load_manifest()

    def load_manifest(self):
        """Load the manifest file"""
        with open(self.manifest_path, 'r') as f:
            self.manifest = json.load(f)

    def generate_global_index(self) -> str:
        """Generate docs/index.md with links to all folders"""
        parts = []

        parts.append("# Repository Documentation Index\n\n")
        parts.append(f"**Repository:** {self.manifest['repo_source']}\n")
        parts.append(f"**Commit:** {self.manifest['commit_sha']}\n")
        parts.append(f"**Generated:** {datetime.utcnow().isoformat()}Z\n\n")
        parts.append("---\n\n")

        # Summary statistics
        parts.append("## Summary\n\n")
        parts.append(f"- **Files scanned:** {self.manifest['files_scanned']:,}\n")
        parts.append(f"- **Folders:** {self.manifest['folders_scanned']:,}\n")
        parts.append(f"- **Total size:** {self.manifest['total_bytes'] / 1024 / 1024:.2f} MB\n")
        parts.append(f"- **Text files:** {self.manifest['stats'].get('type_text', 0):,}\n")
        parts.append(f"- **Binary files:** {self.manifest['stats'].get('type_binary', 0):,}\n")
        parts.append("\n---\n\n")

        # Quick links
        parts.append("## Quick Links\n\n")
        parts.append("- [Root Folder](./index.md)\n")
        parts.append("- [Global Keywords](./keywords.md)\n")
        parts.append("- [Comprehensive Book](./comprehensive_book.md)\n")
        parts.append("- [Verification Report](./verification_report.md)\n")
        parts.append("\n---\n\n")

        # Folder index
        parts.append("## Folder Index\n\n")
        parts.append("### Root\n\n")
        parts.append("- [Root Documentation](./doc.md)\n")
        parts.append("- [Root Index](./index.md)\n")
        parts.append("- [Root Keywords](./sub.md)\n\n")

        # Group folders by top-level directory
        folders_by_top = defaultdict(list)
        for folder in sorted(self.manifest['folders']):
            top_level = Path(folder).parts[0] if folder else 'root'
            folders_by_top[top_level].append(folder)

        for top_level in sorted(folders_by_top.keys()):
            parts.append(f"### {top_level}/\n\n")
            for folder in sorted(folders_by_top[top_level])[:50]:  # Limit to 50 per section
                rel_path = folder
                parts.append(f"- [{folder}/](./{rel_path}/index.md)\n")
            if len(folders_by_top[top_level]) > 50:
                parts.append(f"\n*... and {len(folders_by_top[top_level]) - 50} more folders*\n")
            parts.append("\n")

        parts.append("---\n\n")
        parts.append(f"*Generated by World's Best Repo Book Generator v{self.manifest['generator_version']}*\n")

        return ''.join(parts)

    def generate_global_keywords(self) -> str:
        """Generate docs/keywords.md with merged keywords from all files"""
        parts = []

        parts.append("# Global Keyword Index\n\n")
        parts.append(f"**Generated:** {datetime.utcnow().isoformat()}Z\n\n")
        parts.append("This is a comprehensive A-Z index of all keywords found across the repository.\n\n")
        parts.append("---\n\n")

        # Collect all keywords from all _kw.md files
        print("Collecting keywords from all files...")
        all_keywords = defaultdict(list)

        for file_info in self.manifest['files']:
            if file_info['type'] != 'text':
                continue

            file_path = Path(file_info['path'])
            kw_file = self.docs_root / file_path.parent / f"{file_path.name}_kw.md"

            if kw_file.exists():
                try:
                    with open(kw_file, 'r', encoding='utf-8') as f:
                        content = f.read()
                        # Extract keywords from markdown headers
                        kw_pattern = re.compile(r'^####\s+`([^`]+)`', re.MULTILINE)
                        for match in kw_pattern.finditer(content):
                            keyword = match.group(1)
                            all_keywords[keyword].append(str(file_path))
                except Exception as e:
                    print(f"  Error reading {kw_file}: {e}")

        print(f"Collected {len(all_keywords)} unique keywords")

        # Group by first letter
        keywords_by_letter = defaultdict(list)
        for keyword in all_keywords.keys():
            first_letter = keyword[0].upper()
            if first_letter.isalpha():
                keywords_by_letter[first_letter].append(keyword)
            else:
                keywords_by_letter['#'].append(keyword)

        # Write alphabetical sections
        for letter in sorted(keywords_by_letter.keys()):
            parts.append(f"## {letter}\n\n")
            keywords = sorted(keywords_by_letter[letter])

            # Limit keywords per letter to avoid massive files
            for keyword in keywords[:500]:
                files = all_keywords[keyword]
                parts.append(f"### `{keyword}`\n\n")
                parts.append(f"Found in {len(files)} file(s):\n\n")

                # List up to 10 files
                for file_path in sorted(files)[:10]:
                    # Create relative link
                    rel_link = f"./{file_path.replace(os.sep, '/')}_docs.md"
                    parts.append(f"- [{file_path}]({rel_link})\n")

                if len(files) > 10:
                    parts.append(f"\n*... and {len(files) - 10} more files*\n")

                parts.append("\n")

            if len(keywords) > 500:
                parts.append(f"\n*... and {len(keywords) - 500} more keywords starting with {letter}*\n\n")

        return ''.join(parts)

    def generate_comprehensive_book(self) -> str:
        """Generate comprehensive_book.md by stitching folder docs"""
        parts = []

        parts.append("# Comprehensive Repository Book\n\n")
        parts.append(f"**Repository:** {self.manifest['repo_source']}\n")
        parts.append(f"**Commit:** {self.manifest['commit_sha']}\n")
        parts.append(f"**Generated:** {datetime.utcnow().isoformat()}Z\n\n")
        parts.append("---\n\n")

        # Table of contents
        parts.append("## Table of Contents\n\n")
        parts.append("1. [Introduction](#introduction)\n")
        parts.append("2. [Repository Structure](#repository-structure)\n")
        parts.append("3. [Folder Documentation](#folder-documentation)\n")
        parts.append("4. [File Summaries](#file-summaries)\n")
        parts.append("\n---\n\n")

        # Introduction (from root doc.md)
        parts.append("## Introduction\n\n")
        root_doc = self.docs_root / 'doc.md'
        if root_doc.exists():
            with open(root_doc, 'r', encoding='utf-8') as f:
                parts.append(f.read())
                parts.append("\n")
        parts.append("\n---\n\n")

        # Repository structure (from root index.md)
        parts.append("## Repository Structure\n\n")
        root_index = self.docs_root / 'index.md'
        if root_index.exists():
            with open(root_index, 'r', encoding='utf-8') as f:
                # Skip the header since we have our own
                content = f.read()
                # Remove the first few lines (title and metadata)
                lines = content.split('\n')
                # Find the first horizontal rule and start from there
                for i, line in enumerate(lines):
                    if line.strip() == '---':
                        content = '\n'.join(lines[i+1:])
                        break
                parts.append(content)
                parts.append("\n")
        parts.append("\n---\n\n")

        # Folder documentation chapters
        parts.append("## Folder Documentation\n\n")
        parts.append("This section contains narrative documentation for each major folder in the repository.\n\n")

        # Process folders in order (top-level first, then depth-first)
        all_folders = [''] + sorted(self.manifest['folders'])  # Empty string for root

        for folder in all_folders[:100]:  # Limit to first 100 folders for book size
            folder_path = Path(folder) if folder else Path('.')
            folder_display = str(folder_path) if str(folder_path) != '.' else 'Root'

            parts.append(f"### {folder_display}\n\n")

            # Include folder doc.md
            doc_file = self.docs_root / folder_path / 'doc.md'
            if doc_file.exists():
                try:
                    with open(doc_file, 'r', encoding='utf-8') as f:
                        content = f.read()
                        # Strip header and metadata
                        lines = content.split('\n')
                        in_content = False
                        filtered_lines = []
                        for line in lines:
                            if line.strip() == '---':
                                in_content = True
                                continue
                            if in_content:
                                filtered_lines.append(line)
                        parts.append('\n'.join(filtered_lines))
                        parts.append("\n\n")
                except Exception as e:
                    parts.append(f"*Error reading documentation: {e}*\n\n")

        if len(all_folders) > 100:
            parts.append(f"\n*... and {len(all_folders) - 100} more folders (see individual folder documentation)*\n\n")

        parts.append("---\n\n")

        # File summaries
        parts.append("## File Summaries\n\n")
        parts.append("This section provides brief summaries of key files in the repository.\n\n")

        # Include summaries for important files
        important_patterns = [
            'README', 'LICENSE', 'setup.py', 'pyproject.toml', 'Cargo.toml',
            '__init__.py', 'main.py', 'config', 'Makefile'
        ]

        important_files = []
        for file_info in self.manifest['files']:
            if file_info['type'] != 'text':
                continue
            file_path = Path(file_info['path'])
            file_name = file_path.name
            if any(pattern.lower() in file_name.lower() for pattern in important_patterns):
                important_files.append(file_info)

        # Limit to first 50 important files
        for file_info in important_files[:50]:
            file_path = Path(file_info['path'])
            parts.append(f"### {file_path}\n\n")

            # Link to full documentation
            doc_file = self.docs_root / file_path.parent / f"{file_path.name}_docs.md"
            parts.append(f"[Full Documentation](./{file_path.parent}/{file_path.name}_docs.md)\n\n")

            # Include brief excerpt
            if doc_file.exists():
                try:
                    with open(doc_file, 'r', encoding='utf-8') as f:
                        content = f.read()
                        # Extract overview section
                        overview_match = re.search(r'## Overview\s+(.*?)\s+---', content, re.DOTALL)
                        if overview_match:
                            parts.append(overview_match.group(1).strip())
                            parts.append("\n\n")
                except Exception:
                    pass

        parts.append("---\n\n")
        parts.append(f"*End of Comprehensive Repository Book*\n")
        parts.append(f"*Generated by World's Best Repo Book Generator v{self.manifest['generator_version']}*\n")

        return ''.join(parts)

    def generate_all(self):
        """Generate all global documentation files"""
        results = {}

        # Generate global index
        print("Generating global index...")
        index_content = self.generate_global_index()
        index_path = self.docs_root / 'index.md'
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(index_content)
        results['index'] = {'path': str(index_path), 'size': len(index_content)}
        print(f"  Written: {index_path} ({len(index_content):,} bytes)")

        # Generate global keywords
        print("Generating global keywords...")
        keywords_content = self.generate_global_keywords()
        keywords_path = self.docs_root / 'keywords.md'
        with open(keywords_path, 'w', encoding='utf-8') as f:
            f.write(keywords_content)
        results['keywords'] = {'path': str(keywords_path), 'size': len(keywords_content)}
        print(f"  Written: {keywords_path} ({len(keywords_content):,} bytes)")

        # Generate comprehensive book
        print("Generating comprehensive book...")
        book_content = self.generate_comprehensive_book()
        book_path = self.docs_root / 'comprehensive_book.md'
        with open(book_path, 'w', encoding='utf-8') as f:
            f.write(book_content)
        results['book'] = {'path': str(book_path), 'size': len(book_content)}
        print(f"  Written: {book_path} ({len(book_content):,} bytes)")

        print("\nGlobal documentation complete!")
        return results


if __name__ == '__main__':
    import sys

    repo_root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path('.')
    docs_root = repo_root / 'docs'
    manifest_path = docs_root / 'manifest.json'

    merger = GlobalMerger(repo_root, docs_root, manifest_path)
    results = merger.generate_all()

    print("\nSummary:")
    for name, info in results.items():
        print(f"  {name}: {info['size'] / 1024 / 1024:.2f} MB")
